import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { setTimeout as delay } from 'node:timers/promises'

const API_URL = 'https://api.tarkov.dev/graphql'
const OUTPUT_FILE = path.resolve('src/data/items.ts')
const IMAGE_DIR = path.resolve('public/items')
const ALLERGY_TYPES = new Set(['provisions', 'meds', 'injectors'])
const MAX_ATTEMPTS = 5

function catalogQuery(lang) {
  return `
    query AllergyCatalog {
      items(lang: ${lang}, types: [provisions, meds, injectors]) {
        id
        name
        shortName
        types
        iconLink
      }
    }
  `
}

async function graphqlRequest(query, label) {
  let lastError

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt += 1) {
    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ query }),
      })

      const responseText = await response.text()
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${responseText.slice(0, 1200)}`)
      }

      const payload = JSON.parse(responseText)
      if (payload.errors?.length) {
        throw new Error(payload.errors.map((error) => error.message).join('; '))
      }

      if (!Array.isArray(payload.data?.items)) {
        throw new Error('response did not contain an items array')
      }

      return payload.data.items
    } catch (error) {
      lastError = error
      console.warn(`${label} sync attempt ${attempt}/${MAX_ATTEMPTS} failed: ${error.message}`)
      if (attempt < MAX_ATTEMPTS) await delay(attempt * 3000)
    }
  }

  throw new Error(`${label} catalog sync failed after ${MAX_ATTEMPTS} attempts: ${lastError?.message}`)
}

async function fetchCatalog() {
  const en = await graphqlRequest(catalogQuery('en'), 'EN')
  const ru = await graphqlRequest(catalogQuery('ru'), 'RU')
  return { en, ru }
}

function extensionFor(contentType) {
  if (contentType?.includes('image/webp')) return 'webp'
  if (contentType?.includes('image/jpeg')) return 'jpg'
  if (contentType?.includes('image/svg+xml')) return 'svg'
  return 'png'
}

async function downloadIcon(item) {
  if (!item.iconLink) return null

  try {
    const response = await fetch(item.iconLink)
    if (!response.ok) throw new Error(`HTTP ${response.status}`)

    const extension = extensionFor(response.headers.get('content-type'))
    const fileName = `${item.id}.${extension}`
    const filePath = path.join(IMAGE_DIR, fileName)
    const buffer = Buffer.from(await response.arrayBuffer())
    await writeFile(filePath, buffer)
    return `items/${fileName}`
  } catch (error) {
    console.warn(`Icon skipped for ${item.shortName} (${item.id}): ${error.message}`)
    return null
  }
}

async function mapWithConcurrency(values, concurrency, mapper) {
  const results = new Array(values.length)
  let nextIndex = 0

  async function worker() {
    while (nextIndex < values.length) {
      const index = nextIndex++
      results[index] = await mapper(values[index], index)
    }
  }

  await Promise.all(Array.from({ length: Math.min(concurrency, values.length) }, worker))
  return results
}

const { en, ru } = await fetchCatalog()
const ruById = new Map(ru.map((item) => [item.id, item]))

const selected = en
  .filter((item) => item.types?.some((type) => ALLERGY_TYPES.has(type)))
  .map((item) => {
    const russian = ruById.get(item.id)
    return {
      id: item.id,
      name: item.name ?? item.shortName ?? item.id,
      shortName: item.shortName ?? item.name ?? item.id,
      nameRu: russian?.name ?? item.name ?? item.id,
      shortNameRu: russian?.shortName ?? russian?.name ?? item.shortName ?? item.id,
      category: item.types.includes('provisions') ? 'food' : 'medical',
      types: item.types.filter((type) => ALLERGY_TYPES.has(type)),
      sourceIconLink: item.iconLink,
    }
  })
  .sort((a, b) => a.shortName.localeCompare(b.shortName, 'en'))

if (selected.length < 30) {
  throw new Error(`Only ${selected.length} allergy candidates found; refusing to publish a suspiciously small catalog`)
}

await rm(IMAGE_DIR, { recursive: true, force: true })
await mkdir(IMAGE_DIR, { recursive: true })

const withImages = await mapWithConcurrency(selected, 8, async (item) => ({
  ...item,
  imageLink: await downloadIcon(item),
}))

const items = withImages.map(({ sourceIconLink: _sourceIconLink, ...item }) => item)
const foodCount = items.filter((item) => item.category === 'food').length
const medicalCount = items.length - foodCount
const imageCount = items.filter((item) => item.imageLink).length
const syncedAt = new Date().toISOString()

const output = `import type { TarkovItem } from '../types'\n\n` +
  `// Generated by scripts/sync-items.mjs from Tarkov.dev. Do not edit by hand.\n` +
  `export const catalogSyncedAt = ${JSON.stringify(syncedAt)}\n` +
  `export const items: TarkovItem[] = ${JSON.stringify(items, null, 2)}\n`

await writeFile(OUTPUT_FILE, output, 'utf8')

console.log(`Catalog synced: ${items.length} items (${foodCount} provisions, ${medicalCount} medical/injectors)`)
console.log(`Local icons: ${imageCount}/${items.length}`)
console.log(`Generated: ${OUTPUT_FILE}`)
